name: CI with SonarCloud V2

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_ORG: ${{ secrets.SONAR_ORG }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execution for gradlew
        run: chmod +x gradlew

      - name: Build and test all targets
        run: ./gradlew clean build koverReport

      - name: Run SonarCloud analysis
        run: |
          ./gradlew sonarqube \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
